feat: 공통영역
lemonbase-labs/han-on-boarding-project-new pull request #1
Opened 2022-11-15 07:11 UTC by sehwanforeal

2022-11-15 07:33 UTC, sehwanforeal commented on mockServiceWorker.js
> +/* eslint-disable */
(라이브러리에서 제공하는 코드)

2022-11-15 07:53 UTC, nimuseel requested changes
단순 제안 코멘트 하나 남겼는데, 확인 부탁드려요~

2022-11-15 07:53 UTC, nimuseel commented on src/common/types.ts
> +export type Signup = Login;
[단순 제안]

Signup과 Login 모두 PersonAdd 타입인 듯 한데, 아래처럼 변경하는 것은 어떨지 단순하게 제안해봅니다~ 굳이 PersonAdd가 필요할까? 라는 맥락이인데, Han이 판단해주셔서 넘어가주셔도 됩니다~ 큰 문제는 없으니!

```
export type Login = AddModel<Person>;
export type Signup = AddModel<Person>;
```

2022-11-16 13:50 UTC, JonghwanWon reviewed
덕분에 msw의 구조를 살짝 엿볼 수 있었습니다 👍 
FE-BE 협업 간에 활용도가 어떨까 궁금했지만 도입은 해본적이 없었는데요,
@sehwanforeal 은 이를 제품 개발 시에 사용해본 적이 있나요?

2022-11-16 13:50 UTC, JonghwanWon commented on src/common/components/RedirectByAuthStatus.tsx
> +  const {
[질문]
custom hook으로 작성될 수도 있을 것 같은데, component 형태로 작성 된 이유가 궁금해요

2022-11-16 13:50 UTC, JonghwanWon commented on src/common/hooks/useGetFetch.ts
> +  };
[제안]
요청에 실패한 이후, 재 요청이 성공적이게 된다면, error 정보는 여전히 남아있을 것으로 보이는데요,
요청 할 때에 error를 초기화해주는 것은 어떨까요?

2022-11-16 13:50 UTC, JonghwanWon commented on src/common/hooks/useGetFetch.ts
> +      const axiosError = error as AxiosError;
여기서 잡힐 에러는 axios 요청에서만 발생하는 에러인 것이 확실하기 때문에 AxiosError로 타입표명을 하는군요!

2022-11-16 13:50 UTC, JonghwanWon commented on src/common/hooks/useIsFormFulfilled.ts
> +    const fulfilled = fields.every(({ value }) => !!value);
이 커스텀 훅을 사용하는 부분이 이 PR에서 보이지는 않아
이부분만을 본다면, falsy값을 사용해야 하는 경우에는 대응되지 않을 것으로 보여요.

그전에 form이 모두 채워졌는지를 판단하는 hook이 맞을까요? 😂
(그렇다면 제가 제대로 이해하지 못했나봐요)

2022-11-16 13:50 UTC, JonghwanWon commented on src/common/hooks/useMutationFetch.ts
> +};
[제안]
error가 boolean | string 타입 이라는 것이 조금 헷갈릴 수 있는 부분으로 보여져요.
string | null의 형태로 잡아도 좋을 것 같은데 어떤가요?

2022-11-16 13:50 UTC, JonghwanWon commented on src/common/types.ts
> +export type ID = string;
type alias하는 부분이 바로 이해가 되어서 보기에 좋네요!
더 강력하게 opaque 도 괜찮겠다고 보여요.
```ts
declare const idTag: unique symbol;
type ID = string & {
  __tag: typeof idTag;
};
```

2022-11-16 13:50 UTC, JonghwanWon commented on src/common/types.ts
> +};
Pick을 해도 괜찮을 것 같네요

```ts
export type ReviewFormValues = Pick<Review, 'name' | 'reviewees'> & Pick<Question, 'question' | 'description'>;
```

2022-11-16 13:50 UTC, JonghwanWon commented on src/common/utils/redux.ts
> +      return (state = { person: undefined });
[질문]
새로운 store를 반환하는게 아니라, state를 재할당하는게 맞는건가요?

redux가 많이 바뀌며 slice형태를 써보지 않았지만, 결국 reducer이고 어색한 부분으로 느껴져서 질문드려요 🙏

2022-11-23 04:13 UTC, studroid approved these changes
코멘트 남겨보았습니다!

2022-11-23 04:13 UTC, studroid commented on src/common/utils/redux.ts
> +      return (state = { person: undefined });
redux toolkit을 사용하면 [Immer](https://immerjs.github.io/immer/)를 기본으로 사용하게 되어, state를 mutable한 형태로도 쓸 수 있게 됩니다!

다만 @sehwanforeal 이 쓰신 것은 return을 사용하는데,
위 형태에선 `state.person = payload`, `state.person = undefined` 처럼 사용하는 게 더 직관적이고 편리한 방법이지 않을까 싶네요! ㅎㅎ

2022-11-23 04:13 UTC, studroid commented on src/common/hooks/useGetFetch.ts
> +  });
요렇게 되면 새로 렌더링이 될 때마다 API 호출을 할 것으로 보이는데.. 온보딩 프로젝트라 의도하신 바인 것이지요?

실제 프로덕션에선 API 호출을 렌더링 때마다 하면 백엔드에 부하가 심하게 걸릴 것이기에 코멘트는 남겨봅니다 ㅋㅋ

2022-11-23 04:13 UTC, studroid commented on src/common/utils/bind.ts
> +export function bind<
요 bind는 잘 활용하면 코드 작성 효율이 훨씬 좋은 상태가 될 거 같네요! ㅎㅎ

2022-11-27 17:04 UTC, sehwanforeal commented on mockServiceWorker.js
> +/* eslint-disable */
원래 포함되어있는 것 같습니다 ㅋㅋㅋㅋ

2022-11-27 17:07 UTC, sehwanforeal commented on mockServiceWorker.js
> +/* eslint-disable */
옙! 맞습니다 ㅋㅋ

2022-11-27 17:10 UTC, sehwanforeal commented on src/common/types.ts
> +};
오호 이런 심도높은 논의가 있었군요! type alias VS interface는 항상 타입스크립트에서 재미있는 주제중 하나인 것 같습니다 ! ㅎㅎ 반영하겠습니다

2022-11-27 17:14 UTC, sehwanforeal commented on src/common/hooks/useGetFetch.ts
> +  });
저도 고민했던 부분인데 딱 찾으셨군요 ㅎㅎ 맞습니다.. revalidate 부분을 좀 더 고도화하여 필요한시점에만 revalidate가 호출되게 하고싶었지만 
- 실제 프로덕션 코드가 아님
- 따라서 컴포넌트 리렌더링이 적음
- 구현이 간단함
요러한 이유들로 매 렌더링마다 호출하는방식을 선택했습니다

2022-11-27 17:19 UTC, sehwanforeal commented on src/common/api/useCreateReview.ts
> +  useMutationFetch<Review>({ url: "review", method: "post", data });
`하나의 파일에서 관리한다` 좋아 보이네요! 실제 프로덕션 코드에서는 복잡한 로직들이 포함될 수 있어(parameter 가공. lazy request 로직 등등..) 하나의 파일에 있다면 가독성이 떨어지겠지만 현재는 단순 호출이기 때문에 같은 파일에있다면 응집성에서 많은 이득을 가져갈 수 있겠네요.

2022-11-27 17:23 UTC, sehwanforeal commented
> 덕분에 msw의 구조를 살짝 엿볼 수 있었습니다 👍 FE-BE 협업 간에 활용도가 어떨까 궁금했지만 도입은 해본적이 없었는데요, @sehwanforeal 은 이를 제품 개발 시에 사용해본 적이 있나요?

저도 요번에 처음써봤습니다ㅎㅎ testing등을 위한 도구로도 유용하겠다 라는 생각도 들었네요

2022-11-27 17:26 UTC, sehwanforeal commented on src/common/hooks/useIsFormFulfilled.ts
> +    const fulfilled = fields.every(({ value }) => !!value);
맞습니다! 단순히 value가 모두 falsy한 값이 아닌지 검사하는 훅인데 만약 input에 falsy한 값을 넣아야 할때는 사용불가이겠네요

2022-11-27 17:59 UTC, sehwanforeal commented on src/common/types.ts
> +export type Signup = Login;
동의합니다. 맥락적으로 구분하기위한 목적이였는데 지금 보니 굳이..? 라는 생각이 드네요

2022-11-27 18:08 UTC, sehwanforeal commented on src/common/components/RedirectByAuthStatus.tsx
> +  const {
취향이지만 요런 effect와 같이 독립적인 로직을 가진, 리턴할게 없는 코드일경우에는 ui가 없는 컴포넌트로 만드는것을 선호합니다! 가독성 측면에서 깔끔하다고 생각되서요.
```
useRedirect()
```
보다는
```
<Redirect>
<div>asdasdasd</div>
```

2022-11-27 18:10 UTC, sehwanforeal commented on src/common/hooks/useMutationFetch.ts
> +};
동의합니다. error가 없다. 를 false로 명시해주려는 의도였는데 null도 괜찮아보이고 타입도 깔끔해지겠네요

2022-11-27 18:12 UTC, sehwanforeal commented on src/common/types.ts
> +export type ID = string;
오 요런건 몰랐네요. grahql schema가 생각네요 ㅋㅋ
일단 현재 프로젝트에서는 괜찮을 것 같아 보류하겠습니다 감사합니다!

2022-11-27 19:21 UTC, sehwanforeal commented on src/common/types.ts
> +};
Pick같은 유틸타입 여러개를 & 등으로 결합하고, key까지 다르게 주려고 하면 너무 복잡하고 가독성이 떨어질 것 같아 저는 현재가 괜찮다고 보는데 어떻게생각하시나요?
가독성(어떤 타입에서 참조하는지, 어떤 key가 있는지 한눈에 알아보기 위해), 타입은 참조하되, key는 다르게 주려는 의도였습니다.

2022-11-28 08:56 UTC, JonghwanWon commented on src/common/types.ts
> +};
> One of TypeScript’s core principles is that type checking focuses on the shape that values have.

좋습니다!

의미가 있다면 언제든, 얼마든지 타입은 명시할 수 있다고 생각해요.
단순히, 다시 재사용하기 위해 정의 된 `type interface는 온전히 재사용하는 것이 좋겠다는 생각이었어요.
`Pick`은 하나의 방법으로 제시한 것입니다 😄

조금 더 붙이자면, 동시에 특정 특정 `model interface`의 `property key`가 변경되는 것은 code smell이라고도 생각해요, 그 이유는 예측 불가함에 있는 것 같고요. `Question` 타입의 경우 구조분해(?)되며 `property key`이 변형(`question.title` → `question`, `question.description` → `questionDescription`)되는데 일관성이 조금 떨어지는 부분에서 느꼈어요.

2023-04-01 11:13 UTC, closed without merging