feat: auth기능을 추가한다
lemonbase-labs/han-on-boarding-project-new pull request #4
Opened 2022-11-15 07:24 UTC by sehwanforeal

2022-11-16 14:13 UTC, JonghwanWon commented on src/auth/AuthForm.tsx
> +  };
[제안]
로직과 타입 상 type narrowing되어 data는 분명히 존재해야 할 것으로 보입니다.
헌데 non-null assertion이 사용된 것을 보니 문제가 있군요.
`authRequest`의 타입을 약간 고쳐주면, 더 나이스 해질 것 같아요!

```ts
  authRequest: (
    arg: PersonAdd
  ) => Promise<
    { data: PersonDisplay; error: boolean } | { data: never; error: string }
  >;
```

2022-11-17 01:23 UTC, nimuseel requested changes
제안 하나 남겼습니다!

2022-11-17 01:23 UTC, nimuseel commented on src/auth/AuthForm.tsx
> +
[제안]

error를 직접 if문에서 거르는 것 보다 try catch를 사용하는 것은 어떤가요?

```
try {
 const reponse = await authRequest(values);
 login(response.data);
 push('/review');
} catch(error) {
  message.error(...);
}
```

2022-11-23 04:33 UTC, studroid approved these changes

2022-11-23 04:33 UTC, studroid commented on src/auth/AuthForm.tsx
> +const useAuthForm = ({ formName, authRequest }: Props) => {
프로덕션 코드에선 요렇게 함수 및 일반 컴포넌트를 선언하는 용도로는 현재 function keyword를 쓰고 있습니다! 참고로..!

2022-11-27 17:58 UTC, sehwanforeal commented on src/auth/AuthForm.tsx
> +const useAuthForm = ({ formName, authRequest }: Props) => {
감사합니다! 일단은 요번 프로젝트에서는 arrow function을 유지해도 될까요?

2022-11-27 19:34 UTC, sehwanforeal commented on src/auth/AuthForm.tsx
> +  };
never사용 좋네요!

2022-11-27 19:34 UTC, sehwanforeal commented on src/auth/AuthForm.tsx
> +
다른 PR에서 코멘트 남겼습니다!

2023-04-01 11:10 UTC, closed without merging