feat: 리뷰 기능을 추가한다
lemonbase-labs/han-on-boarding-project-new pull request #5
Opened 2022-11-15 07:25 UTC by sehwanforeal

2022-11-16 14:20 UTC, JonghwanWon commented on src/review/ReviewForm.tsx
> +      >
[제안]
질문과 질문 설명이 flat하게 form에 저장되고 요청할때에, 기본값을 세팅할때에 조합/분해되는 로직들이 많이 보이는데,
object형태로 값을 관리하면 이런 부분들이 많이 간결해지지 않을까라는 생각이 들어요.

```ts
<Form.Item label="질문" name={['question', 'title']} rules={[{ required: true }]}>
  <Input data-test="review-question-input" />
</Form.Item>
<Form.Item label="질문설명" name={['question', 'description']} rules={[{ required: true }]}>
  <Input data-test="review-question-input" />
</Form.Item>
```

즉, request - response - form 의 타입과 데이터가 일치하는 상태라고 해야할까요

2022-11-17 01:29 UTC, nimuseel requested changes
코멘트 남겼어요~ 고생하셨습니다 👍

2022-11-17 01:29 UTC, nimuseel commented on src/review/CreateReview.tsx
> +};
[질문]

interface가 아닌 type을 쓰시는 이유가 있을까요? 단순 궁금!

2022-11-17 01:29 UTC, nimuseel commented on src/review/CreateReview.tsx
> +
[제안]

여기도 이전 PR과 마찬가지로 try catch로 에러 핸들링을 하는 것은 어떤가요?

2022-11-17 01:29 UTC, nimuseel commented on src/review/ReviewTable.tsx
> +    message.success({
[제안]

여기도 이전 PR과 마찬가지로 try catch로 에러 핸들링을 하는 것은 어떤가요?

2022-11-17 01:29 UTC, nimuseel commented on src/review/ReviewTable.tsx
> +
[제안]

이 부분은 컴포넌트 상단으로 올려도 될 것 같은 느낌이군요..!?

2022-11-17 01:29 UTC, nimuseel commented on src/review/UpdateReview.tsx
> +
[제안]

여기도 이전 PR과 마찬가지로 try catch로 에러 핸들링을 하는 것은 어떤가요?

2022-11-23 04:39 UTC, studroid commented on src/review/CreateReview.tsx
> +};
관련 댓글도 [여기](https://github.com/lemonbase-labs/han-on-boarding-project-new/pull/1#discussion_r1029998559) 달았어서 링크 ㅎㅎ

2022-11-23 04:52 UTC, studroid approved these changes
멋진 코드 잘 보았습니다!! ㅎㅎㅎ

2022-11-23 04:52 UTC, studroid commented on src/review/ReviewPage.tsx
> +    <div data-test="review-page">
문득 든 생각인데, 요런 `data-test`에 들어가는 문자열들은 따로 상수로 빼놓고, 테스트 케이스에서도, 실제 코드에서도 똑같이 상수를 쓰도록 연결하면 테스트 관리가 더 용이할 듯해요 ㅎㅎ

2022-11-23 04:52 UTC, studroid commented on src/review/ReviewForm.tsx
> +  ({ form, onSubmit, onFieldsChange, people, shouldSubmitActive }) => (
요렇게 항목이 많고 prop과 다른 상태들을 바게 되는 경우 bind가 정말 유용해보이네요! ㅎㅎ
component의 prop이 hook 쪽으로 간다는 것만 주지하고 사용하기만 하면 효과적일 듯하군요!!

2022-11-27 19:46 UTC, sehwanforeal commented on src/review/ReviewForm.tsx
> +      >
와우 베리굿입니다!!

2022-11-27 19:48 UTC, sehwanforeal commented on src/review/CreateReview.tsx
> +};
문법적 선호 and 습관 이였습니다 ㅋㅋ ㅎㅎ @studroid 의 코멘트 참조하여 변경하겠습니다!

2022-11-27 19:52 UTC, sehwanforeal commented on src/review/UpdateReview.tsx
> +
이전 PR에서 논의!

2022-11-27 19:52 UTC, sehwanforeal commented on src/review/ReviewTable.tsx
> +    message.success({
이전 PR에서 논의!

2022-11-27 19:53 UTC, sehwanforeal commented on src/review/CreateReview.tsx
> +
이전 PR에서 논의!

2022-11-27 20:00 UTC, sehwanforeal commented on src/review/CreateReview.tsx
> +
[try-catch 관련 논의 공간]
try-catch를 사용하지 않은것은 사실 개인취향이라, @nimuseel 의 의견이 궁금합니다. 

try-catch 를 사용했을시
- error가 어느 시점(어느 라인)에서 발생했는지 파악하기 힘듬
- 여러 에러를 구분하기 위해서는 if문 혹은 또다른 try-catch문이 필요함
- 따라서 디버깅이 어려움

if 를 사용했을시
- error가 있을때의 상황을 직접 컨트롤 
- error시점을 명시적으로 표시

요러한 이유로 axios 등에서 에러를 throw되는게 아니라면 if로 흐름을 제어하는것을 선호합니다. (그렇기 떄문에 실제 fetch하는 useMutationFetch에서 throw가 아닌 error라는 변수를 return하게 작성) 도 요런것에 대해서 논의해본적이없는데 다른분들의 의견도 궁금하네요!

2022-11-27 20:10 UTC, sehwanforeal commented on src/review/ReviewPage.tsx
> +    <div data-test="review-page">
오, 그렇게하면 유지보수하기 더 쉬워지겠네요. 

요거에 대해서 처음에 고민되는점이 있었는데 공유드려요. (결론은 @studroid 의 제안이 좋아보인다)
`e2e 테스트와 애플리케이션 소스코드는 완전히 분리한다 - e2e테스트는 end에서 test하기 때문에 태스트하는 애플리케이션에 의존성이 없어야 한다` 라는 의도가 있었는데 코드상에서 상수이긴 해도 같은 모듈을 참조한다면 분리된게 아닌게 되니 고민 이였어요. 이후 `상수를 공유한다고해서 얻게되는 문제가 있을까` 라는 고민을 해봤는데 결론은 없다! 였습니다 ㅎㅎ

2022-11-27 20:11 UTC, sehwanforeal commented on src/review/ReviewPage.tsx
> +    <div data-test="review-page">
지금 시점에서 요거를 옮기게되면 살짝 노가다 느낌이 있는데 일단 생략하려는데 괜찮을.. 까요?

2022-11-28 22:26 UTC, studroid commented on src/review/ReviewPage.tsx
> +    <div data-test="review-page">
당연하죠 ㅋㅋㅋ

2023-04-01 11:09 UTC, closed without merging